# Generated by Django 4.0.3 on 2022-07-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0007_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(unique=True, upload_to='uploads//'),
        ),
    ]
